export type MessageType =
  | "ALIMTALK"
  | "FRIENDTALK"
  | "SMS"
  | "LMS"
  | "MMS"
  | "NSA"
  | "VOICE"
  | "FAX"
  | "RCS_SMS"
  | "RCS_LMS"
  | "RCS_MMS"
  | "RCS_TPL"
  | "RCS_ITPL"
  | "RCS_LTPL";

export type MessageStatus = "PENDING" | "SENT" | "FAILED";

export const KNOWN_MESSAGE_STATUSES: MessageStatus[] = [
  "PENDING",
  "SENT",
  "FAILED",
];

export const QUEUED_MESSAGE_STATUS: MessageStatus = "PENDING";

export const normalizeMessageStatus = (status: unknown): MessageStatus => {
  const raw = typeof status === "string" ? status.trim().toUpperCase() : "";

  if (raw === "PENDING" || raw === "SENT" || raw === "FAILED") {
    return raw;
  }

  return QUEUED_MESSAGE_STATUS;
};

export type MessageVariables = Record<
  string,
  string | number | boolean | Date | null | undefined
>;

export interface MessageButton {
  name: string;
  /**
   * Provider-dependent. Common values: "WL" (web link), "AL" (app link), ...
   */
  type: string;
  urlPc?: string;
  urlMobile?: string;
}

export type MessageBinaryInput =
  | {
      /**
       * URL or file path (provider-dependent).
       */
      ref: string;
      filename?: string;
      contentType?: string;
    }
  | {
      bytes: Uint8Array;
      filename?: string;
      contentType?: string;
    }
  | {
      blob: Blob;
      filename?: string;
      contentType?: string;
    };

export interface MessageMedia {
  /**
   * Image attachment (used by MMS, FriendTalk image, RCS_MMS, ...).
   */
  image?: MessageBinaryInput;
}

export interface CommonSendOptions {
  /**
   * Correlation id generated by KMsg (or provided by the caller).
   * Providers must echo this value back in SendResult.messageId.
   */
  messageId?: string;
  /**
   * Optional routing hint to force a specific provider by id.
   */
  providerId?: string;
  to: string;
  /**
   * Sender number / sender id. Optional at KMsg layer; providers may require it.
   */
  from?: string;
  /**
   * Common delivery options understood by multiple providers.
   */
  options?: {
    scheduledAt?: Date;
    /**
     * Country code for providers that support it (e.g. SOLAPI).
     * Examples: "82", "+82".
     */
    country?: string;
    customFields?: Record<string, string>;
  };
  /**
   * Provider-specific escape hatch (use sparingly).
   */
  providerOptions?: Record<string, unknown>;
}

export interface KakaoSendOptions {
  profileId?: string;
  plusId?: string;
  disableSms?: boolean;
  adFlag?: boolean;
  buttons?: unknown[];
  imageId?: string;
  /**
   * FriendTalk image upload link hint (SOLAPI).
   */
  imageLink?: string;
  // biome-ignore lint/suspicious/noExplicitAny: provider-specific extras
  [key: string]: any;
}

export interface AlimTalkFailoverOptions {
  enabled?: boolean;
  fallbackChannel?: "sms" | "lms";
  fallbackContent?: string;
  fallbackTitle?: string;
}

export type SendWarningCode =
  | "FAILOVER_UNSUPPORTED_PROVIDER"
  | "FAILOVER_PARTIAL_PROVIDER"
  | "FALLBACK_CONTENT_MISSING"
  | (string & {});

export interface SendWarning {
  code: SendWarningCode;
  message: string;
  details?: Record<string, unknown>;
}

export interface NaverSendOptions {
  talkId?: string;
  /**
   * Override the template identifier for NSA (provider-specific).
   */
  templateId?: string;
  disableSms?: boolean;
  variables?: MessageVariables;
  buttons?: unknown[];
  // biome-ignore lint/suspicious/noExplicitAny: provider-specific extras
  [key: string]: any;
}

export interface VoiceSendOptions {
  voiceType?: "FEMALE" | "MALE";
  headerMessage?: string;
  tailMessage?: string;
  replyRange?: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;
  counselorNumber?: string;
  // biome-ignore lint/suspicious/noExplicitAny: provider-specific extras
  [key: string]: any;
}

export interface FaxSendOptions {
  fileIds?: string[];
  fileUrls?: string[];
  // biome-ignore lint/suspicious/noExplicitAny: provider-specific extras
  [key: string]: any;
}

export interface RcsSendOptions {
  brandId?: string;
  /**
   * Override template identifier for RCS_*TPL types.
   */
  templateId?: string;
  copyAllowed?: boolean;
  variables?: MessageVariables;
  mmsType?: "M3" | "S3" | "M4" | "S4" | "M5" | "S5" | "M6" | "S6";
  commercialType?: boolean;
  disableSms?: boolean;
  buttons?: unknown[];
  additionalBody?: {
    title?: string;
    description?: string;
    imageId?: string;
    buttons?: unknown[];
    // biome-ignore lint/suspicious/noExplicitAny: provider-specific extras
    [key: string]: any;
  };
  // biome-ignore lint/suspicious/noExplicitAny: provider-specific extras
  [key: string]: any;
}

export interface SmsSendOptions extends CommonSendOptions {
  type: "SMS" | "LMS" | "MMS";
  text: string;
  /**
   * LMS/MMS subject.
   */
  subject?: string;
  /**
   * Media attachments. For backwards compatibility, `imageUrl` is treated as a legacy alias
   * for `media.image.ref` by some providers.
   */
  media?: MessageMedia;
  /**
   * Optional image URL for MMS (provider-specific).
   */
  imageUrl?: string;
  variables?: MessageVariables;
}

export interface AlimTalkSendOptions extends CommonSendOptions {
  type: "ALIMTALK";
  templateId: string;
  variables: MessageVariables;
  kakao?: KakaoSendOptions;
  failover?: AlimTalkFailoverOptions;
}

export interface FriendTalkSendOptions extends CommonSendOptions {
  type: "FRIENDTALK";
  text: string;
  media?: MessageMedia;
  imageUrl?: string;
  buttons?: MessageButton[];
  variables?: MessageVariables;
  kakao?: KakaoSendOptions;
}

export interface NsaSendOptions extends CommonSendOptions {
  type: "NSA";
  templateId: string;
  variables: MessageVariables;
  naver?: NaverSendOptions;
}

export interface VoiceMessageSendOptions extends CommonSendOptions {
  type: "VOICE";
  text: string;
  variables?: MessageVariables;
  voice?: VoiceSendOptions;
}

export interface FaxMessageSendOptions extends CommonSendOptions {
  type: "FAX";
  fax: FaxSendOptions;
}

export interface RcsTextSendOptions extends CommonSendOptions {
  type: "RCS_SMS" | "RCS_LMS" | "RCS_MMS";
  text: string;
  subject?: string;
  media?: MessageMedia;
  imageUrl?: string;
  variables?: MessageVariables;
  rcs?: RcsSendOptions;
}

export interface RcsTemplateSendOptions extends CommonSendOptions {
  type: "RCS_TPL" | "RCS_ITPL" | "RCS_LTPL";
  templateId: string;
  variables: MessageVariables;
  rcs?: RcsSendOptions;
}

export type SendOptions =
  | SmsSendOptions
  | AlimTalkSendOptions
  | FriendTalkSendOptions
  | NsaSendOptions
  | VoiceMessageSendOptions
  | FaxMessageSendOptions
  | RcsTextSendOptions
  | RcsTemplateSendOptions;

export type SmsDefaultSendInput = Omit<SmsSendOptions, "type" | "text"> & {
  type?: undefined;
  /**
   * SMS text. If omitted, `content` is used.
   */
  text?: string;
  /**
   * Alias for `text`.
   */
  content?: string;
};

/**
 * Developer-facing input type.
 * - SMS defaults allow omitting `type` and using `content`.
 * - Other channels are modeled as discriminated unions on `type`.
 */
export type SendInput = SendOptions | SmsDefaultSendInput;

export interface SendResult {
  /**
   * Correlation id (equals the request `messageId`).
   */
  messageId: string;
  providerId: string;
  providerMessageId?: string;
  status: MessageStatus;
  type: MessageType;
  to: string;
  warnings?: SendWarning[];
  raw?: unknown;
}
