-- Generated by scripts/print-schema.ts from src/tracking-schema.ts.
-- Apply it with: psql "$DATABASE_URL" -f sql/schema.sql

CREATE TABLE IF NOT EXISTS "kmsg_delivery_tracking" (
  "message_id" TEXT PRIMARY KEY,
  "provider_id" TEXT NOT NULL,
  "provider_message_id" TEXT NOT NULL,
  "type" VARCHAR(64) NOT NULL,
  "to" VARCHAR(64) NOT NULL,
  "from" VARCHAR(64),
  "status" VARCHAR(64) NOT NULL,
  "provider_status_code" VARCHAR(64),
  "provider_status_message" TEXT,
  "sent_at" TIMESTAMPTZ,
  "delivered_at" TIMESTAMPTZ,
  "failed_at" TIMESTAMPTZ,
  "requested_at" TIMESTAMPTZ NOT NULL,
  "scheduled_at" TIMESTAMPTZ,
  "status_updated_at" TIMESTAMPTZ NOT NULL,
  "attempt_count" INTEGER NOT NULL DEFAULT 0,
  "last_checked_at" TIMESTAMPTZ,
  "next_check_at" TIMESTAMPTZ NOT NULL,
  "last_error" JSONB,
  "metadata" JSONB
);

CREATE INDEX IF NOT EXISTS "idx_kmsg_delivery_due" ON "kmsg_delivery_tracking" ("status", "next_check_at");

CREATE INDEX IF NOT EXISTS "idx_kmsg_delivery_provider_msg" ON "kmsg_delivery_tracking" ("provider_id", "provider_message_id");

CREATE INDEX IF NOT EXISTS "idx_kmsg_delivery_requested_at" ON "kmsg_delivery_tracking" ("requested_at");
