import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

type AuditFinding =
  | "astro-import"
  | "astro-component"
  | "mdx-import"
  | "jsx-tag"
  | "starlight-component";

type FileAudit = {
  findings: AuditFinding[];
  path: string;
};

const repoRoot = path.resolve(import.meta.dir, "../..");
const docsContentRoot = path.join(repoRoot, "apps/docs/src/content/docs");
const reportPath = path.join(
  repoRoot,
  "docs/migration/hono-docs-source-audit.md",
);
const checkMode = process.argv.includes("--check");

const findingLabels: Record<AuditFinding, string> = {
  "astro-component": "Uses `.astro` component references",
  "astro-import": "Imports Astro-specific modules",
  "jsx-tag": "Contains JSX-style component tags",
  "mdx-import": "Contains ESM imports/exports that need rewrite",
  "starlight-component": "Uses Starlight components or loaders",
};

async function walkFiles(dirPath: string, output: string[]): Promise<void> {
  const entries = await readdir(dirPath, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = path.join(dirPath, entry.name);
    if (entry.isDirectory()) {
      await walkFiles(fullPath, output);
      continue;
    }

    if (entry.name.endsWith(".md") || entry.name.endsWith(".mdx")) {
      output.push(fullPath);
    }
  }
}

function relativePath(filePath: string): string {
  return path.relative(repoRoot, filePath).replaceAll(path.sep, "/");
}

function stripCodeFences(markdown: string): string {
  let stripped = markdown.replace(/```[\s\S]*?```/g, "");
  stripped = stripped.replace(/~~~[\s\S]*?~~~/g, "");
  return stripped;
}

function detectFindings(markdown: string): AuditFinding[] {
  const findings = new Set<AuditFinding>();
  const proseOnly = stripCodeFences(markdown);

  if (
    /^import\s.+from\s+["'][^"']+["'];?/m.test(proseOnly) ||
    /^export\s/m.test(proseOnly)
  ) {
    findings.add("mdx-import");
  }

  if (/@astrojs\/starlight|astro:content/.test(proseOnly)) {
    findings.add("astro-import");
    findings.add("starlight-component");
  }

  if (/\.astro["']/.test(proseOnly)) {
    findings.add("astro-component");
  }

  if (
    /<(LinkButton|Code|Tabs|TabItem|Card|Aside|Steps)\b/.test(proseOnly) ||
    /<\/(LinkButton|Code|Tabs|TabItem|Card|Aside|Steps)>/.test(proseOnly)
  ) {
    findings.add("starlight-component");
    findings.add("jsx-tag");
  }

  if (/<[A-Z][A-Za-z0-9]*([\s/>]|\/>)/.test(proseOnly)) {
    findings.add("jsx-tag");
  }

  return [...findings].sort();
}

function summarize(audits: FileAudit[]): {
  compatible: FileAudit[];
  incompatible: FileAudit[];
  totals: Record<AuditFinding, number>;
} {
  const totals = {
    "astro-component": 0,
    "astro-import": 0,
    "jsx-tag": 0,
    "mdx-import": 0,
    "starlight-component": 0,
  } satisfies Record<AuditFinding, number>;

  for (const audit of audits) {
    for (const finding of audit.findings) {
      totals[finding] += 1;
    }
  }

  return {
    compatible: audits.filter((audit) => audit.findings.length === 0),
    incompatible: audits.filter((audit) => audit.findings.length > 0),
    totals,
  };
}

function renderFindingList(findings: AuditFinding[]): string {
  return findings.map((finding) => findingLabels[finding]).join(", ");
}

function renderReport(audits: FileAudit[]): string {
  const { compatible, incompatible, totals } = summarize(audits);

  const incompatibleRows = incompatible
    .map(
      (audit) => `| \`${audit.path}\` | ${renderFindingList(audit.findings)} |`,
    )
    .join("\n");

  const compatibleRows = compatible
    .slice(0, 40)
    .map((audit) => `- \`${audit.path}\``)
    .join("\n");

  const remainingCompatibleCount = Math.max(compatible.length - 40, 0);

  return `# Hono Docs Source Audit

This file is generated by \`bun run docs:migration:audit:hono\`.

This audit checks the current docs source tree for Astro/Starlight/MDX-specific constructs that block a direct move to a plain Markdown + Hono SSG pipeline.

## Summary

- Total files scanned: ${audits.length}
- Files compatible with plain Markdown rendering today: ${compatible.length}
- Files requiring migration work before Hono SSG can render them directly: ${incompatible.length}

## Blocking Construct Counts

| Finding | Files |
| --- | ---: |
| Uses Astro-specific modules | ${totals["astro-import"]} |
| Uses \`.astro\` component references | ${totals["astro-component"]} |
| Contains ESM imports/exports | ${totals["mdx-import"]} |
| Contains JSX-style component tags | ${totals["jsx-tag"]} |
| Uses Starlight components or loaders | ${totals["starlight-component"]} |

## Files Requiring Rewrite

| File | Findings |
| --- | --- |
${incompatibleRows || "| None | None |"}

## Plain Markdown-Compatible Files

${compatibleRows || "- None"}
${remainingCompatibleCount > 0 ? `\n- ...and ${remainingCompatibleCount} more` : ""}

## Migration Interpretation

- Files in the "rewrite" table need either Markdown normalization or custom rendering components before the Astro docs app can be retired.
- Files in the compatible list can move first into the Hono pipeline with minimal risk.
- The highest-value rewrite targets are the top-level landing pages and snippet pages because they currently depend on Starlight-only components.
`;
}

async function collectAudits(): Promise<FileAudit[]> {
  const files: string[] = [];
  await walkFiles(docsContentRoot, files);

  const sortedFiles = files.sort();
  return Promise.all(
    sortedFiles.map(async (filePath) => {
      const markdown = await readFile(filePath, "utf8");
      return {
        findings: detectFindings(markdown),
        path: relativePath(filePath),
      } satisfies FileAudit;
    }),
  );
}

async function main(): Promise<void> {
  const audits = await collectAudits();
  const next = `${renderReport(audits)}\n`;

  let current = "";
  try {
    current = await readFile(reportPath, "utf8");
  } catch {
    current = "";
  }

  if (checkMode) {
    if (current !== next) {
      console.error(
        `Hono docs source audit is out of date: ${relativePath(reportPath)}`,
      );
      process.exit(1);
    }
    console.log(`ok: ${relativePath(reportPath)}`);
    return;
  }

  if (current === next) {
    console.log(`unchanged: ${relativePath(reportPath)}`);
    return;
  }

  await mkdir(path.dirname(reportPath), { recursive: true });
  await writeFile(reportPath, next, "utf8");
  console.log(`generated: ${relativePath(reportPath)}`);
}

await main();
