import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";

type ApiSourceEntry = {
  docsRelativePath: string;
  exportKey: string;
  packageDir: string;
  packageName: string;
  repoRelativePath: string;
};

type PackageExportEntry = {
  namespace: null | string;
  source: ApiSourceEntry;
};

const repoRoot = path.resolve(import.meta.dir, "../..");
const inventoryPath = path.join(repoRoot, "apps/docs/api-sources.json");
const outputRoot = path.join(repoRoot, "apps/docs-hono/content/docs");
const checkMode = process.argv.includes("--check");

const packageBuildOrder = [
  "packages/core",
  "packages/template",
  "packages/provider",
  "packages/messaging",
  "packages/analytics",
  "packages/channel",
  "packages/webhook",
  "packages/k-msg",
] as const;

function packageSlug(packageName: string): string {
  return packageName.replace(/^@k-msg\//, "");
}

function toPosix(value: string): string {
  return value.replaceAll(path.sep, "/");
}

function exportNamespace(exportKey: string): null | string {
  if (exportKey === ".") {
    return null;
  }

  const trimmed = exportKey.replace(/^\.\//, "");
  return trimmed.replaceAll("/", "_").replaceAll("-", "_");
}

function declarationPathFromSource(source: ApiSourceEntry): string {
  const packageRoot = path.join(repoRoot, source.packageDir);
  const sourcePath = path.join(repoRoot, source.repoRelativePath);
  const relativeToPackage = path.relative(packageRoot, sourcePath);
  return relativeToPackage.replace(/^src\//, "dist/").replace(/\.ts$/, ".d.ts");
}

function routePrefix(locale: "en" | "ko"): string {
  return locale === "en" ? "/en" : "";
}

function stripGeneratedHeader(markdown: string): string {
  return markdown
    .replace(/^<!-- Do not edit this file\.[\s\S]*?-->\r?\n\r?\n/, "")
    .trimStart();
}

function frontmatterBlock(params: {
  description?: string;
  sourcePath: string;
  title?: string;
}): string {
  const lines = ["---"];
  if (params.title) {
    lines.push(`title: ${JSON.stringify(params.title)}`);
  }
  if (params.description) {
    lines.push(`description: ${JSON.stringify(params.description)}`);
  }
  lines.push(`sourcePath: ${JSON.stringify(params.sourcePath)}`);
  lines.push("---", "");
  return lines.join("\n");
}

function headingFromMarkdown(markdown: string): string | null {
  const match = markdown.match(/^##\s+(.+)$/m);
  return match?.[1]?.trim() ?? null;
}

function apiIndexMarkdown(locale: "en" | "ko", packageNames: string[]): string {
  const title = locale === "ko" ? "API 문서" : "API Reference";
  const description =
    locale === "ko"
      ? "API Extractor 기반의 API 문서입니다."
      : "API reference generated with API Extractor.";
  const links = packageNames
    .map((name) => {
      const slug = packageSlug(name);
      return `- [${name}](${routePrefix(locale)}/api/${slug}/)`;
    })
    .join("\n");

  return `${frontmatterBlock({
    description,
    sourcePath: "apps/docs/api-sources.json",
    title,
  })}${links}\n`;
}

async function readInventory(): Promise<ApiSourceEntry[]> {
  const raw = await readFile(inventoryPath, "utf8");
  return JSON.parse(raw) as ApiSourceEntry[];
}

async function runCommand(args: string[], cwd: string): Promise<void> {
  const proc = Bun.spawn(args, {
    cwd,
    stderr: "inherit",
    stdout: "inherit",
  });
  const exitCode = await proc.exited;
  if (exitCode !== 0) {
    throw new Error(
      `Command failed (${exitCode}): ${args.join(" ")} (cwd: ${cwd})`,
    );
  }
}

async function buildTypeDeclarations(): Promise<void> {
  for (const packageDir of packageBuildOrder) {
    await runCommand(
      ["bun", "run", "--cwd", packageDir, "build:types"],
      repoRoot,
    );
  }
}

function buildSyntheticEntry(
  entries: PackageExportEntry[],
  workDir: string,
): string {
  const lines: string[] = [];

  for (const entry of entries) {
    const packageRoot = path.join(repoRoot, entry.source.packageDir);
    const declarationPath = path.join(
      packageRoot,
      declarationPathFromSource(entry.source),
    );
    let modulePath = toPosix(path.relative(workDir, declarationPath)).replace(
      /\.d\.ts$/,
      "",
    );
    if (!modulePath.startsWith(".")) {
      modulePath = `./${modulePath}`;
    }

    if (entry.namespace === null) {
      lines.push(`export * from "${modulePath}";`);
    } else {
      lines.push(`export * as ${entry.namespace} from "${modulePath}";`);
    }
  }

  return `${lines.join("\n")}\n`;
}

function extractorConfig(workDirName: string, slug: string): string {
  return `${JSON.stringify(
    {
      $schema:
        "https://developer.microsoft.com/json-schemas/api-extractor/v7/api-extractor.schema.json",
      apiReport: {
        enabled: false,
        reportFileName: slug,
      },
      compiler: {
        overrideTsconfig: {
          $schema: "http://json.schemastore.org/tsconfig",
          compilerOptions: {
            module: "preserve",
            moduleResolution: "bundler",
            skipLibCheck: true,
            target: "es2022",
          },
          files: [`<projectFolder>/${workDirName}/entrypoint.d.ts`],
        },
      },
      docModel: {
        apiJsonFilePath: `<projectFolder>/${workDirName}/model/${slug}.api.json`,
        enabled: true,
      },
      dtsRollup: {
        enabled: false,
      },
      mainEntryPointFilePath: `<projectFolder>/${workDirName}/entrypoint.d.ts`,
      messages: {
        compilerMessageReporting: {
          default: {
            logLevel: "warning",
          },
        },
        extractorMessageReporting: {
          "ae-extra-release-tag": {
            logLevel: "none",
          },
          "ae-forgotten-export": {
            logLevel: "none",
          },
          "ae-missing-release-tag": {
            logLevel: "none",
          },
          default: {
            logLevel: "warning",
          },
        },
        tsdocMessageReporting: {
          default: {
            logLevel: "warning",
          },
        },
      },
      projectFolder: "..",
      tsdocMetadata: {
        enabled: false,
      },
    },
    null,
    2,
  )}\n`;
}

type OutputPage = {
  outputRelativePath: string;
  routePath: string;
  sourcePath: string;
  stem: string;
};

function outputPageForStem(params: {
  locale: "en" | "ko";
  packageEntries: PackageExportEntry[];
  packageName: string;
  stem: string;
}): null | OutputPage {
  const slug = packageSlug(params.packageName);
  const rootSourcePath =
    params.packageEntries.find((entry) => entry.namespace === null)?.source
      .repoRelativePath ??
    params.packageEntries[0]?.source.repoRelativePath ??
    "apps/docs/api-sources.json";

  if (params.stem === "index") {
    return null;
  }

  if (params.stem === slug) {
    return {
      outputRelativePath: "index.md",
      routePath: `${routePrefix(params.locale)}/api/${slug}/`,
      sourcePath: rootSourcePath,
      stem: params.stem,
    };
  }

  const prefix = `${slug}.`;
  const suffix = params.stem.startsWith(prefix)
    ? params.stem.slice(prefix.length)
    : params.stem;
  const segments = suffix.split(".").filter(Boolean);

  if (segments.length === 0) {
    return {
      outputRelativePath: "index.md",
      routePath: `${routePrefix(params.locale)}/api/${slug}/`,
      sourcePath: rootSourcePath,
      stem: params.stem,
    };
  }

  const namespaceSource = params.packageEntries.find(
    (entry) => entry.namespace === segments[0],
  )?.source.repoRelativePath;
  const sourcePath = namespaceSource ?? rootSourcePath;
  const outputRelativePath =
    segments.length === 1
      ? path.join(segments[0], "index.md")
      : path.join(...segments.slice(0, -1), `${segments.at(-1)}.md`);

  return {
    outputRelativePath,
    routePath: `${routePrefix(params.locale)}/api/${slug}/${segments.join("/")}/`,
    sourcePath,
    stem: params.stem,
  };
}

function rewriteMarkdownLinks(
  markdown: string,
  linkMap: Map<string, string>,
): string {
  return markdown.replace(
    /\]\((?:\.\/)?([^)#]+\.md)(#[^)]+)?\)/g,
    (match, linkTarget: string, hash: string | undefined) => {
      const routePath = linkMap.get(path.basename(linkTarget));
      if (!routePath) {
        return match;
      }

      return `](${routePath}${hash ?? ""})`;
    },
  );
}

async function listMarkdownFiles(dirPath: string): Promise<string[]> {
  const entries = await readdir(dirPath, { withFileTypes: true });
  return entries
    .filter((entry) => entry.isFile() && entry.name.endsWith(".md"))
    .map((entry) => path.join(dirPath, entry.name))
    .sort();
}

async function copyMarkdownFolder(params: {
  packageEntries: PackageExportEntry[];
  packageName: string;
  sourceDir: string;
}): Promise<void> {
  const markdownFiles = await listMarkdownFiles(params.sourceDir);

  for (const locale of ["ko", "en"] as const) {
    const linkMap = new Map<string, string>([
      ["index.md", `${routePrefix(locale)}/api/readme/`],
    ]);
    const resolvedPages = new Map<string, OutputPage>();

    for (const filePath of markdownFiles) {
      const stem = path.basename(filePath, ".md");
      const outputPage = outputPageForStem({
        locale,
        packageEntries: params.packageEntries,
        packageName: params.packageName,
        stem,
      });

      if (!outputPage) {
        continue;
      }

      resolvedPages.set(filePath, outputPage);
      linkMap.set(path.basename(filePath), outputPage.routePath);
    }

    for (const [filePath, outputPage] of resolvedPages) {
      const raw = await readFile(filePath, "utf8");
      const stripped = stripGeneratedHeader(raw);
      const rewritten = rewriteMarkdownLinks(stripped, linkMap);
      const title = headingFromMarkdown(rewritten) ?? undefined;
      const localeDir = locale === "en" ? path.join("en", "api") : "api";
      const targetPath = path.join(
        outputRoot,
        localeDir,
        packageSlug(params.packageName),
        outputPage.outputRelativePath,
      );
      const next = `${frontmatterBlock({
        description: `API reference generated from ${params.packageName}.`,
        sourcePath: outputPage.sourcePath,
        title,
      })}${rewritten}\n`;

      await mkdir(path.dirname(targetPath), { recursive: true });
      await writeFile(targetPath, next, "utf8");
    }
  }
}

async function generatePackageDocs(
  packageName: string,
  packageEntries: PackageExportEntry[],
): Promise<void> {
  if (packageEntries.length === 0) {
    console.warn(`No inventory entries found for ${packageName}; skipping.`);
    return;
  }

  const packageDirAbsolute = path.join(
    repoRoot,
    packageEntries[0].source.packageDir,
  );
  const workDirName = ".api-extractor-docs";
  const workDir = path.join(packageDirAbsolute, workDirName);
  const slug = packageSlug(packageName);
  const markdownDir = path.join(workDir, "markdown");
  const modelDir = path.join(workDir, "model");

  await rm(workDir, { force: true, recursive: true });
  await mkdir(modelDir, { recursive: true });

  await writeFile(
    path.join(workDir, "entrypoint.d.ts"),
    buildSyntheticEntry(packageEntries, workDir),
    "utf8",
  );
  await writeFile(
    path.join(workDir, "api-extractor.json"),
    extractorConfig(workDirName, slug),
    "utf8",
  );

  try {
    await runCommand(
      [
        "bun",
        "x",
        "api-extractor",
        "run",
        "--local",
        "--config",
        path.join(workDir, "api-extractor.json"),
      ],
      repoRoot,
    );
    await runCommand(
      [
        "bun",
        "x",
        "api-documenter",
        "markdown",
        "-i",
        modelDir,
        "-o",
        markdownDir,
      ],
      repoRoot,
    );

    await copyMarkdownFolder({
      packageEntries,
      packageName,
      sourceDir: markdownDir,
    });
  } finally {
    await rm(workDir, { force: true, recursive: true });
  }
}

async function main(): Promise<void> {
  const inventory = await readInventory();
  const grouped = new Map<string, PackageExportEntry[]>();

  for (const entry of inventory) {
    const list = grouped.get(entry.packageName) ?? [];
    list.push({
      namespace: exportNamespace(entry.exportKey),
      source: entry,
    });
    grouped.set(entry.packageName, list);
  }

  if (checkMode) {
    console.error(
      "generate-api-extractor-docs.ts does not currently support --check; run the generator and inspect outputs instead.",
    );
    process.exit(1);
  }

  await buildTypeDeclarations();

  await rm(path.join(outputRoot, "api"), { force: true, recursive: true });
  await rm(path.join(outputRoot, "en", "api"), {
    force: true,
    recursive: true,
  });

  const packageNames = packageBuildOrder
    .map(
      (packageDir) =>
        inventory.find((entry) => entry.packageDir === packageDir)?.packageName,
    )
    .filter((packageName): packageName is string => Boolean(packageName));

  for (const packageName of packageNames) {
    await generatePackageDocs(packageName, grouped.get(packageName) ?? []);
  }

  await mkdir(path.join(outputRoot, "api"), { recursive: true });
  await mkdir(path.join(outputRoot, "en", "api"), { recursive: true });
  await writeFile(
    path.join(outputRoot, "api", "README.md"),
    apiIndexMarkdown("ko", packageNames),
    "utf8",
  );
  await writeFile(
    path.join(outputRoot, "en", "api", "README.md"),
    apiIndexMarkdown("en", packageNames),
    "utf8",
  );

  console.log("generated API Extractor docs for docs-hono");
}

await main();
