/**
 * Prints the Postgres schema for the delivery tracking table, built by the
 * library's buildDeliveryTrackingSchemaSql() from the options the Worker's
 * store uses. Regenerate sql/schema.sql after changing src/tracking-schema.ts:
 *
 *   bun scripts/print-schema.ts > sql/schema.sql
 */
import { trackingSchemaSql } from "../src/tracking-schema";

console.log(`-- Generated by scripts/print-schema.ts from src/tracking-schema.ts.
-- Apply it with: psql "$DATABASE_URL" -f sql/schema.sql

${trackingSchemaSql()}`);
