/**
 * K-Message: Korean Multi-Channel Messaging Platform
 * Lightweight facade focused on basic send flow
 */

export {
  type ActiveKidRolloutBucket,
  type ActiveKidRolloutPolicy,
  type AesGcmFieldCryptoProviderOptions,
  type AwsKmsKeyResolverClient,
  type AwsKmsKeyResolverOptions,
  assertFieldCryptoConfig,
  type CryptoEnvelope,
  createAesGcmFieldCryptoProvider,
  createAwsKmsKeyResolver,
  createDefaultMasker,
  createEnvKeyResolver,
  createNoopFieldCryptoProvider,
  createRefreshableKeyResolver,
  createRollingKeyResolver,
  createStaticKeyResolver,
  createVaultTransitKeyResolver,
  type EnvKeyResolverOptions,
  type ErrorRetryPolicyIssue,
  type ErrorRetryPolicyMode,
  type ErrorRetryPolicyNormalizeOptions,
  type ErrorRetryPolicyValidationResult,
  ErrorUtils,
  type FieldCryptoAad,
  type FieldCryptoCircuitState,
  type FieldCryptoConfig,
  type FieldCryptoControlScope,
  type FieldCryptoControlSignalEvent,
  type FieldCryptoDecryptInput,
  type FieldCryptoEncryptInput,
  FieldCryptoError,
  type FieldCryptoErrorKind,
  type FieldCryptoErrorMetadata,
  type FieldCryptoFailMode,
  type FieldCryptoHashInput,
  type FieldCryptoKeyContext,
  type FieldCryptoMaskInput,
  type FieldCryptoMetricEvent,
  type FieldCryptoMetricName,
  type FieldCryptoOpenFallback,
  type FieldCryptoPolicyOptions,
  type FieldCryptoPolicyValidationIssue,
  type FieldCryptoPolicyValidationResult,
  type FieldCryptoProvider,
  type FieldMode,
  fail,
  getPollableStatuses,
  getRolloutKnownKids,
  isKMsgDeliveryStatus,
  isKMsgMessageType,
  isKMsgTerminalStatus,
  isPollableDeliveryStatus,
  isTerminalDeliveryStatus,
  type KeyResolver,
  type KeySetState,
  type KeySetStateProvider,
  KMSG_DELIVERY_STATUSES,
  KMSG_MESSAGE_TYPES,
  KMSG_POLLABLE_STATUSES,
  KMSG_TERMINAL_STATUSES,
  KMsgError,
  KMsgErrorCode,
  type MessageType,
  type NormalizedProviderError,
  type NormalizedProviderErrorSources,
  type NormalizeProviderErrorOptions,
  normalizeErrorRetryPolicy,
  normalizePhoneForHash,
  normalizeProviderError,
  ok,
  type Provider,
  parseErrorRetryPolicyFromJson,
  type RefreshableKeyResolverOptions,
  type Result,
  resolveFieldMode,
  type SendInput,
  type SendOptions,
  type SendResult,
  type StaticKeyResolverOptions,
  selectActiveKidByRollout,
  toCiphertextEnvelopeString,
  type VaultTransitKeyResolverClient,
  type VaultTransitKeyResolverOptions,
  validateErrorRetryPolicy,
  validateFieldCryptoConfig,
} from "@k-msg/core";
export { KMsg } from "@k-msg/messaging";
